### PR TITLE
Add DGL UI for basic chorus variant

### PR DESCRIPTION
**Pull request by SpotlightKid**
* Just two buttons for chorus Type I and II for now.
* About/Info dialog to be added by a later PR.
* ...and maybe opening website by clicking URL at bottom.
* Might be integrated into a UI for the advanced chorus variants later or remain as a separate "idiot proof" version. To be decided.

screenshot-panel-basic

### CODE REVIEW

**Comment by jpcima** [comment]
It's very nice work. I think, there is some potential ways that we may make this better.

- the file `ArtworkHera.cpp` will be expensive to track under git, better to remove it
- maybe rather have one version of the chorus in the end; this project is beyond experimental stage, and more versions mean more work for maintaining the whole
- in principle we could even do without a stereo/mono variant. This is not currently available to DPF afaik, but there exists a property `connectionOptional` for the input second channel by which we might select stereo mode automatically.
https://lv2plug.in/ns/lv2core#connectionOptional

**Comment by SpotlightKid** [comment]
> the file `ArtworkHera.cpp` will be expensive to track under git, better to remove it

Ok, I removed both the source and header file. We have to remember, though, to generate these files before creating a release source tarball, because you need Python, Numpy and PIL for that.


... which is why the Travis build promptly failed. :-/

**Comment by jpcima** [comment]
Oh this, no problem just add deps here.
https://github.com/jpcima/rc-effect-playground/blob/8f95c31ac62919204dc187e4571326fa5383631a/.travis.yml#L24

Also I forgot, please credit yourself somewhat for the work, not only me. (on UI or metadata or both)

**Comment by SpotlightKid** [comment]
I fixed the travis build and squashed the commits in the branch.

**Comment by SpotlightKid** [comment]
Re. different variants of the plugin. As you suggested in #4, I would like to get the project in a beta release shape first and then tackle the advanced UI later.

**Comment by SpotlightKid** [comment]
> please credit yourself somewhat for the work

Yes, that's part of #4 (`AUTHORS` file) and #9. In the `LICENSE`  file I'll just add `et al.` after your name and put a note with e reference to `AUTHORS` in the readme.

**Review by jpcima — APPROVED** [review]
It's good :)
OK to merge it when you want

**Comment by SpotlightKid** [comment]
Ok, do it :)

**Pull request merged**
